### ISSUE TITLE
LR1110 APP key?

### ISSUE THREAD

**Issue by Lozeonjyu** [Lora-net/LoRaMac-node#1040]
Hi,

I was trying to test under TTN but only found Dev EUI, Join EUI and element pin under se-identity.h

What about the other keys like app key and how do i achieve them? 

Thanks

**Comment by mluis1** [comment]
When we get some more time we will try to re-work the LR1110 provisioning in order to ease its setup.

In the meantime you can refer to the answers provided on issue #984 for further details.

In the future it would be nice if you could post this kind of questions on the project [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab.
