### ISSUE TITLE
Type Mismatch in LR1110

### ISSUE THREAD

**Issue by Devilal-Prajapat** [Lora-net/LoRaMac-node#1083]
There is Multiple Data Types and Structure element mismatch in LR1110.
Radio.c &  lr1110_radio_types.h lr1110_system_types.h

**Comment by mluis1** [comment]
We are currently updating all radio drivers to newer versions and the kind of issues that you are reporting should have been fixed
.
You can take a look at [v5.0.0-branch](https://github.com/Lora-net/LoRaMac-node/tree/v5.0.0-branch) in order to preview the changes that have been done. So far we successfully have run Class A pre-certification tests using every supported radio (SX126x, SX127x and LR1110).

For further information about the changes that will be introduced for v5.0.0 release please refer to #1239 discussion topic.
