### ISSUE TITLE
Question about SetNextChannel Function

### ISSUE THREAD

**Issue by mpt8153** [Lora-net/LoRaMac-node#116]
In function ScheduleTx there's a call to SetNextChannel function:
    // Select channel
    while( SetNextChannel( &dutyCycleTimeOff ) == false )
    {
        // Set the default datarate
        LoRaMacParams.ChannelsDatarate = LoRaMacParamsDefaults.ChannelsDatarate;

#if defined( USE_BAND_433 ) || defined( USE_BAND_780 ) || defined( USE_BAND_868 )
        // Re-enable default channels LC1, LC2, LC3
        LoRaMacParams.ChannelsMask[0] = LoRaMacParams.ChannelsMask[0] | ( LC( 1 ) + LC( 2 ) + LC( 3 ) );
#endif
    }

If I try to transmit a message to an unsupported DR then ScheduleTX doesn't exit from while  loop. For example if the enabled channels are EU863-870 default channels (LC1, LC2, LC3) and I try to send a message with DR6 the problem arise. Is a way to avoid this?  Or is a way to check if channel is enabled befrore schedule TX?
BR

**Comment by djaeckle** [comment]
Hi mpt8153,

thanks for the report. Your statement is correct. If you set the default DR to >DR_5, and no channel is available, it will not exit from the loop. Thus, the default datarate should be a value, which is always applicable with respect to the region. E.g. in EU868, the datarates supported by the default channels is DR_0 to DR_5. Otherwise it is possible that you losse connectivity (regardless of the loop).
What you could do is to query the MAC if the channel you have added is activated. However, you also have to take the duty cycle into account - if the channel is active, it could happen that the MAC cannot transmit due to the duty cycle restrictions.

We will provide an update to limit the configuration of the default DR.
