### ISSUE TITLE
PingSlotPeriodicity incorrect type

### ISSUE THREAD

**Issue by JulianvDoorn** [Lora-net/LoRaMac-node#1167]
After compiling the project using a C++ compiler I noticed a narrowing cast from uint8_t to bool, C++ thus rejects the compilation, while I suspect that C does not check such thing. 

I added a permalink to the line underneath. I suspect instead of bool an uint8_t is desired.

https://github.com/Lora-net/LoRaMac-node/blob/05353ff70bec5349a26b23a02168accb0ea03ad9/src/apps/LoRaMac/common/LmHandler/LmHandler.h#L114

**Comment by mluis1** [comment]
Thanks for the report.

As background we are currently implementing and validating the Class B certification process. This work is still in progress and will take some time to get finalized as it is not an easy task.

The specific issue has already been fixed in our internal repository as follows

![image](https://user-images.githubusercontent.com/5763295/134877560-062833e5-068b-4914-a5ad-c2e4e5cfc585.png)

```
SHA-1: 72922f0cf43335e370b1142d870f503a8e4261f5

* Fixed LmHandlerParams_t PingSlotPeriodicity field type from bool to uint8_t
```

If you don't mind I close this issue. We will update the GitHub repository once we have finalized the Class B certification validation.
