### ISSUE TITLE
Unused member in struct SX126x ( PacketStatus)

### ISSUE THREAD

**Issue by StressTest** [Lora-net/LoRaMac-node#1222]
/src/radio/sx126x.h
```
 /*!
* Radio hardware and global parameters
*/
typedef struct SX126x_s
{
     Gpio_t        Reset; //!< Not used in radio and project
     Gpio_t        BUSY; //!< Not used in radio and project
     Gpio_t        DIO1; //!< Not used in radio and project
     Gpio_t        DIO2; //!< Not used in radio and project
     Gpio_t        DIO3; //!< Not used in radio and project
     Spi_t         Spi;  //!< Not used in radio and project
    PacketParams_t PacketParams;
     PacketStatus_t PacketStatus; //!< Not used in project
    ModulationParams_t ModulationParams;
}SX126x_t;
```
/src/radio/sx126x/radio.c
```
PacketStatus_t RadioPktStatus;
...........
/*!
 * Radio hardware and global parameters
 */
SX126x_t SX126x;

```
Member (field) _PacketStatus_ is not used in the linked files or in the examples. Variable _RadioPktStatus_ is used.
P.S. I think it's better to move Reset, BUSY, DIO1, DIO2, SIO3, Spi to somewhere in the directory like /board. Now we get a mixture of the program model of SX126x IC and the hardware implementation of the board. (I want to initialize the periphery through STM32 HAL, but the /radio directory already contains structures with microcontroller settings - it's not good)

**Comment by mluis1** [comment]
You are right. It looks like we have forgot to do some cleanup at some point in time.

We are currently updating all radio drivers to newer versions and your recommendations are already part of this work.
You can take a look at [v5.0.0-branch](https://github.com/Lora-net/LoRaMac-node/tree/v5.0.0-branch) in order to preview the changes that have been done. So far we successfully have run Class A pre-certification tests using every supported radio (SX126x, SX127x and LR1110).

For further information about the changes that will be introduced for v5.0.0 release please refer to #1239 discussion topic.
