### ISSUE TITLE
unused Rejoin2CycleTimer and OnRejoin2CycleTimerEvent

### ISSUE THREAD

**Issue by sborshch** [Lora-net/LoRaMac-node#1226]
LoRaWAN specification says, that Rejoin type 2 can only be transmitted following a ForceRejoinReq MAC command. So there is no need for timer and timer handler in LoRaMac.c.

**Comment by mluis1** [comment]
In our internal repository we have already fixed this issue while re-working and implementing missing features for the ReJoinReq management. These fixes are still under validation that's why we did not made them public yet.

Please refer to issue https://github.com/Lora-net/LoRaMac-node/issues/1220

If you don't mind we close this issue.
