### ISSUE TITLE
DevNonce of zero never used due to post increment followed by assignment

### ISSUE THREAD

**Issue by dmeehan1968** [Lora-net/LoRaMac-node#1367]
According to the LoRaWAN spec v1.0.4:

> DevNonce is a counter starting at 0 when the end-device is initially powered up and incremented with every Join-Request.

As implemented, when there is no prior DevNonce established (initial power on, no persisted NVM data), the stack holds 0 as the initial DevNonce, but the following code in LoRaMacCrypto.c post increments and then assigned, leading to the first DevNonce transmitted to be 1.

https://github.com/Lora-net/LoRaMac-node/blob/55f83f90ddbc4bc6aabd34a3262d3870548b3577/src/mac/LoRaMacCrypto.c#L994-L996

The correct implementation should have included the assignment and post increment in the same statement, with the original random implementation left unaffected.  USE_RANDOM_DEV_NONCE is hardcoded as 0 so without patching the header, random nonce values are no longer used (as per spec).

```c
#if ( USE_RANDOM_DEV_NONCE == 1 )
    uint32_t devNonce = 0;
    SecureElementRandomNumber( &devNonce );
    CryptoNvm->DevNonce = devNonce;
    macMsg->DevNonce = CryptoNvm->DevNonce;
#else
    macMsg->DevNonce = CryptoNvm->DevNonce++;
#endif
```

**Comment by mluis1** [comment]
We believe that the current implementation is correct.

The specification can be interpreted in 2 different ways
- Yours: `DevNonce` is incremented after the `JoinReq` message has been built
- Ours: `DevNonce` is incremented before the  `JoinReq` message has been built

From our understanding the 
- DevNonce is initialized to 0 -> DevNonce is a counter starting at 0 when the end-device is initially powered up (consensual)
- DevNonce is incremented for every `JoinReq` -> meaning that when we build the `JoinReq` message we first increment the `DevNonce`. (non consensual)

The reason why we think our interpretation is the best is due to the fact that the network servers need as well to initialize the `DevNonce` to 0 and they need to verify that it is incremented for every received JoinReq.

In case one uses your proposed interpretation the network servers would have to add a special case to handle a `JoinReq` with a `DevNonce` equal to 0 as in this case the value does not increment.

As we are not sure how the network server developers have interpreted the specification we think it is better to first increment the value.

The only advantage of your proposal is that one would have one extra possible `JoinReq` out of 65536. We don't believe it is worth it changing this.
