### ISSUE TITLE
Porting guide Link does not work

### ISSUE THREAD

**Issue by charlesfayal** [Lora-net/LoRaMac-node#1394]

**Comment by mluis1** [comment]
I suppose that you mean the link provided under the README.md file.
https://github.com/Lora-net/LoRaMac-node/blob/master/README.md#supported-platforms

I have just tried it and everything looks to work as expected.

I just noticed that the link is pointing to version v4.5.1 instead of version v4.6.0. However if I remember well the porting guide has not changed since quite some time now.

The link will be fixed once we execute the v4.7.0 release,
