### ISSUE TITLE
any plan to configure the project for openstm32?

### ISSUE THREAD

**Issue by pschaus** [Lora-net/LoRaMac-node#241]
I'm developing on MacOS but coIDE and Keil only seem to be available for windows :-(
Tx

Pierre

**Comment by RaulMungai** [comment]
Hello Pierre,

Try to use Parallels, is fantastic and allow to execute app win and OsX
contemporary.
I use windows fo my IDE on my MacBook.

Sent from Raul mobile device

Il giorno 24 mag 2017, alle ore 10:14, pschaus <notifications@github.com>
ha scritto:

I'm developing on MacOS but coIDE and Keil only seem to be available for
windows :-(
Tx

Pierre

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lora-net/LoRaMac-node/issues/241>, or mute the thread

**Comment by temporaryaccount** [comment]
> I'm developing on MacOS but coIDE and Keil only seem to be available for windows :-(
It is really straight-forward using OpenSTM32. Just create a new project with your microcontroller selected (or using STM32CubeMX), then import the library files from this repository that are going to be used in your project, and you are set up. Then gradually import application code from the samples, be careful not to have two versions of microcontroller initialization code (from the IDE itself and from the sample application code).

**Comment by mluis1** [comment]
With issue #346 we have introduced a cmake build system. ([Build environment](https://github.com/Lora-net/LoRaMac-node/wiki/Development-environment).) 
Now the project can be built on the major OS. One can also use Visual Studio Code as IDE.
