### ISSUE TITLE
Sleep mode

### ISSUE THREAD

**Issue by gnob417** [Lora-net/LoRaMac-node#390]
Hi, can i stop RX mode or TX mode by using Radio.Sleep() ? 
and can i stop triggering interrupt by using TimerStop()? 

@nestorayuso 
please help me.

**Comment by mluis1** [comment]
Yes for both questions.

**Comment by gnob417** [comment]
Did you do experiment about what i ask?
I use TimerStop() for rx1, rx2 before rx1 or rx2 starts, however, listen mode still triggered..

**Comment by mluis1** [comment]
We are sorry but we don't really understand the issue that you are encountering or what you are trying to achieve.

As this issue is not really related to this project I would recommend that you try to ask your questions on the [LoRa Community](http://semtech.force.com/lora) portal.

But, trying to answer your question at least what we understand, if you set the radio to sleep mode in the middle of a transmission then it is normal that the frame is not received on the other side (the frame isn't received completely).
The radio should be put in sleep mode only once you have either a TxDone, RxDone, RxTimeout, RxError or TxTimeout.
