### ISSUE TITLE
rssi calculation

### ISSUE THREAD

**Issue by gnob417** [Lora-net/LoRaMac-node#420]
Hi,
there is rssi calculation code like below.
```
int16_t rssi = SX1272Read( REG_LR_PKTRSSIVALUE );
if( snr < 0 )
{
     SX1272.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET + rssi + ( rssi >> 4 ) + snr;
}
else
{
      SX1272.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET + rssi + ( rssi >> 4 ); 
}
```

However, in specification by semtech, https://www.semtech.com/uploads/documents/sx1272.pdf ,
they say 

> The same formula can be re-used to evaluate the signal strength of the received packet:
>  Packet Strength (dBm) = -139 + PacketRssi * 0.25, (with LnaBoost On and SNR >= 0)
> Due to the nature of the LoRa modulation, it is possible to receive packets below the noise floor. In this situation, the SNR
> is used in conjunction of the PacketRssi to compute the signal strength of the received packet:
>  Packet Strength (dBm) = -139 + PacketRssi + PacketSnr * 0.25, (with LnaBoost On and SNR < 0)

I think code and documentation is quite different. 
what's the gap between these two sources?

**Comment by GuntherSchulz** [comment]
@gnob417 
Let's deal with snr >= 0 case first.
The document you refer to, on the very same page as the formulas you quote (Note 3), specifically states that when SNR>=0, the true result is better given by RSSI=-139+16/15*PacketRssi [due to linearity issues].
Now 17/16 is used as an approximation to 16/15 (accurate to within 0.391%, i.e. less than 4 parts error per thousand).
I'm sure you'll agree, especially within the context of an ISR, that this minor error in accuracy is easily sacrificed so as not to have an expensive, time-consuming division and multiplication, but rather a cheap fast bit-shift and add.

The snr < 0 case.
Note at this point in the code, snr already has the value PacketSnr/4 (calculated immediately above the code you quote).
You might decide on the trade-off on using 17/16*PacketRssi (which is 6.25% too high) and essentially the only difference between branches being an addition of snr or not [again think ISR speed], or using the correct value of PacketRssi
