### ISSUE TITLE
SAML21 RTC comparison data mismatch

### ISSUE THREAD

**Issue by damyvv** [Lora-net/LoRaMac-node#454]
Hi everyone.

The following compare does not seem right.
https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/boards/SAML21/rtc-board.c#L136

The RtcGetElapsedAlarmTime is in milliseconds as seen below:
https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/boards/SAML21/rtc-board.c#L115-L118

And the TimeoutDuration is in ticks as seen below:
https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/boards/SAML21/rtc-board.c#L78

Could this be an issue? If so, what would be the effect of such an issue?

Thanks in advance.

**Comment by x893** [comment]
I port SAML21 to SAMR34J18B and all works fine. But only with internal OSC32

**Comment by KaDw** [comment]
> 
> 
> I port SAML21 to SAMR34J18B and all works fine. But only with internal OSC32

@x893 You used RTC as clock source like in SAML21? Can you share your implementation? I'm having trouble with joining in OTAA mode, Join Request is sent, gateway responds with Join Accept but device is not processing it (RX window might be shifted?). I tried OSC32 and XOSC32, no luck. ABP is working fine I get correct data, although everytime I send data I get Tx timeout message (DIO0 interrupt is not triggered).

I saw a lot of issues that mentioned Tx timeout/OTAA problems and mainly they were caused by timing issues. There are two functions RtcMs2Tick and RtcTick2Ms. It is worth mentioning that clock for this RTC is in fact 1.024kHz, not exactly 1kHz. RtcTick2Ms takes that into account, RtcMs2Tick does not.  

```
uint32_t RtcMs2Tick( TimerTime_t milliseconds )
{
    return ( uint32_t )( milliseconds );
}

TimerTime_t RtcTick2Ms( uint32_t tick )
{
    uint32_t seconds = tick >> 10; // seconds = tick / 1024

    tick = tick & 0x3FF; // mask to 1024
    return ( ( seconds * 1000 ) + ( ( tick * 1000 ) >> 10 ) );
}
```

I changed it to (we lose some precision anyway):
```
uint32_t RtcMs2Tick( TimerTime_t milliseconds )
{
    uint32_t tick = (milliseconds << 10) / 1000;

    return ( uint32_t )( tick );
}
```
Now when I measure it with scope it is closer to value set by TimerSetValue(). But this is not working anyway. Still get Tx timeouts and OTAA fail.
Anyone managed to run classA demo in OTAA mode with SAML21 or SAMR34 board?
