### ISSUE TITLE
Why 9 LoraMac default channels are specified in EU868 band

### ISSUE THREAD

**Issue by FoujanetG** [Lora-net/LoRaMac-node#49]
Hi,

The LoraWan specification defines 3 default channels(LC1,LC2 and LC3) to guarantee a minimal channelset between and-device and gateways.

In LoraMac-Board.h 9 channels are defined and are used in LoraMac.c.
 I don't understand the utility.  New channels are sent by the operator, and the range is 863-870MHz. 

thanks ,

Guillaume F.

**Comment by mluis1** [comment]
Hi,

You are right the specification only specifies the 3 default channels.

In our implementation we have added the other channels in order to have the motes using all the available modems on the gateway. This was most useful for personalized devices.

Please note also that not every server implementation will send the creation of supplemental channels.

Please also note that even if the server creates new channels over the air and there was already channels defined those should be replaced.

For the next release we have moved those channels definition from the LoRaWAN mac layer implementation to the application layer (main.c file). You can decide if you want to enable by default the creation of those channels or not.

```C
...
#define USE_SEMTECH_DEFAULT_CHANNEL_LINEUP          1

#if( USE_SEMTECH_DEFAULT_CHANNEL_LINEUP == 1 ) 

#define LC4                { 867100000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC5                { 867300000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC6                { 867500000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC7                { 867700000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC8                { 867900000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC9                { 868800000, { ( ( DR_7 << 4 ) | DR_7 ) }, 2 }

#endif

#endif

...
#if defined( USE_BAND_868 )
                LoRaMacTestSetDutyCycleOn( LORAWAN_DUTYCYCLE_ON );

#if( USE_SEMTECH_DEFAULT_CHANNEL_LINEUP == 1 ) 
                LoRaMacChannelAdd( 3, ( ChannelParams_t )LC4 );
                LoRaMacChannelAdd( 4, ( ChannelParams_t )LC5 );
                LoRaMacChannelAdd( 5, ( ChannelParams_t )LC6 );
                LoRaMacChannelAdd( 6, ( ChannelParams_t )LC7 );
                LoRaMacChannelAdd( 7, ( ChannelParams_t )LC8 );
                LoRaMacChannelAdd( 8, ( ChannelParams_t )LC9 );
#endif

#endif

...

```
