### ISSUE TITLE
RxChainCalibration() doesn't use region specific frequency for HF

### ISSUE THREAD

**Issue by judedcruz** [Lora-net/LoRaMac-node#536]
Hi,

git tag: 4.4.1

I noticed that the function RxChainCalibration() in file sx1276.c sets the HF frequency to 868MHz. Shouldn't it be setting the HF based on the region?

Thanks,
Jude

**Comment by mluis1** [comment]
Ideally you are right. In order to have better image rejection one should launch the image calibration each time the RF frequency change is bigger than 10 MHz but, it should also be done when temperature changes.

The drawback is that the calibration takes around 10 ms to be completed. Thus, if we run it every time it would take more time to go from sleep to Tx/Rx as well as we would increase the power consumption.

Everything is a question of compromise. As of today, we didn’t saw real degradation on reception performances but, if you noticed such degradation you could change the implementation to at least apply the calibration parameters each time the new RF frequency and previous one difference is bigger than 10 MHz.

To do so at radio reset:
1.	Launch calibration at 434 MHz
2.	Store results in an array
3.	Launch calibration at 866 MHz
4.	Store results in an array
5.	Launch calibration at 907 MHz
6.	Store results in an array
7.	Launch calibration at 917 MHz
8.	Store results in an array
9.	Launch calibration at 927 MHz
10.	Store results in an array

Each time the `Radio.SetChannel` function is called.
1.	Read current frequency
2.	Compute current frequency and new frequency difference
3.	If difference bigger than 10 MHz apply the calibration values previously stored on the array corresponding to the frequency range you are trying to set.
