### ISSUE TITLE
SRV_MAC_DEVICE_TIME_ANS

### ISSUE THREAD

**Issue by daniwebCH** [Lora-net/LoRaMac-node#608]
What is going with the timers derived from the RTC when we modify it while receiving the command SRV_MAC_DEVICE_TIME_ANS ?

**Comment by mluis1** [comment]
Nothing happens to the RTC hardware it just keeps increment its internal values which never reset.
There is also nothing happening to the timers that are derived as the RTC hardware is untouched.

When receiving the `DeviceTimeAns` the `SysTimeSet` function only computes an offset to the current RTC value. 
Thus, each time we perform a `SysTimeGet` function call we read the current RTC value and we add the offset value in order to obtain the current time.
