### ISSUE TITLE
Strange behavior of SX126x buffer

### ISSUE THREAD

**Issue by alex00971** [Lora-net/LoRaMac-node#609]
Hi
I have weird issue with SX126x (both sx1261 and sx1262)
When I write to buffer , and read it back again, it returns different data.
I wrote a small test,before enabling LORA MAC, and everything is OK,(Reading the same data as it wrote)
But when LORA MAC is setup , exactly before sending data, I write to buffer and read it back , I get different data.
What's the issue ?
This is the code, I added read buffer.
![image](https://user-images.githubusercontent.com/9721014/49573607-dcff7400-f957-11e8-93c0-52686c79c8b0.png)
And this is the result I get : 
  <info> app: >>Buffer writing @ 0x00 , 23 bytes
  00  91  4D  01  D0  7E  D5  B3  70  7C  2E  87  DE  5F  3B  D7  
  00  01  00  9B  D5  0B  B2  
  <info> app: <<Buffer reading @ 0x00 , 23 bytes
  05  B0  01  DE  07  99  D2  C1  BC  16  09  E3  06  47  80  53  
  A0  D9  73  1F  06  1B  6A  

Any idea what could be the reason ?
I'm driving it with NRF52 chip.

I'm using mac Version : 4.4.1

**Comment by mluis1** [comment]
The observed behavior is the expected one.
The buffer read and write pointer indexes are different.

These kind of questions aren't really related to this project thus, we kindly ask that you post your question on the [Semtech LoRa Community](https://semtech.force.com/lora) forum in order to get further details.
