### ISSUE TITLE
FLASH/RAM footprint

### ISSUE THREAD

**Issue by dba351** [Lora-net/LoRaMac-node#715]
I want to evaluate the FLASH RAM footprint in order to dimensioning microcontroller for a new product. I've tried to compile loramac for STM32L152 and STM32L476 nucleo boards:
```
cmake -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-arm-none-eabi.cmake" \
           -DAPPLICATION="LoRaMac" \
           -DCLASS="classA" \
           -DCLASSB_ENABLED="OFF" \
           -DACTIVE_REGION="LORAMAC_REGION_EU868" \
           -DREGION_EU868="ON" \
           -DREGION_US915="ON" \
           -DREGION_CN779="OFF" \
           -DREGION_EU433="OFF" \
           -DREGION_AU915="OFF" \
           -DREGION_AS923="OFF" \
           -DREGION_CN470="OFF" \
           -DREGION_KR920="OFF" \
           -DREGION_IN865="OFF" \
           -DREGION_RU864="OFF" \
           -DBOARD="NucleoL476" .. && make -j4
```
or
```
cmake -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-arm-none-eabi.cmake" \
           -DAPPLICATION="LoRaMac" \
           -DCLASS="classA" \
           -DCLASSB_ENABLED="OFF" \
           -DACTIVE_REGION="LORAMAC_REGION_EU868" \
           -DREGION_EU868="ON" \
           -DREGION_US915="ON" \
           -DREGION_CN779="OFF" \
           -DREGION_EU433="OFF" \
           -DREGION_AU915="OFF" \
           -DREGION_AS923="OFF" \
           -DREGION_CN470="OFF" \
           -DREGION_KR920="OFF" \
           -DREGION_IN865="OFF" \
           -DREGION_RU864="OFF" \
           -DBOARD="NucleoL152" .. && make -j4
```

I found The application compiled for STM32L4 requires more than 10Kbytes  of flash compared to
STM32L1 image. Why there is this difference?

**Comment by mluis1** [comment]
The things that I can think about to explain this observation are:

1. The 2 processors are different and if I'm not mistaken have small differences on the instruction set. 
STM32L4 is a CortexM4 while the STM32L1 is a CortexM3.
2. The peripherals libraries furnished by ST are different as the micro controllers may have different versions of the same peripheral hardware.
3. The STM32L4 has no EEPROM emulation flash interface. In order to have the same behavior on the STM32L4 we have included the [x-cube-eeprom](https://www.st.com/en/embedded-software/x-cube-eeprom.html) package which uses a non negligible amount of FLASH and RAM memories.
