### ISSUE TITLE
Where do i save the device configuration information?

### ISSUE THREAD

**Issue by KwonTae-young** [Lora-net/LoRaMac-node#784]
I am a beginner of LoRaWAN.
My guess is that the configuration of the LoRaWAN end-node device needs to be saved somewhere.
```
Device EUI
Application EUI
Application KEY
Public Network use?
Default Tx Duty Cycle
Setting Tx Duty Cycle
is ClassA?
is ClassB?
...
...
```

I have only thought about the above information, but besides this, various information needs to be stored in the device.
I also think that I can store this information in Flash on the MCU, but I'm not sure if that's the right idea.(flash life cycle)
Where does LoRaWAN end-node devices typically store this information? EEPROM? M-RAM?

I'm sorry I do not have enough English. :)
Thank you.

**Comment by mluis1** [comment]
Please take a look at the `NvmCtxMgmt.c` file. There you will see everything that requires to be stored in a persistent memory.

In this project there are 2 examples of storage.
1. stm32l0 devices we store the information in the provide internal EEPROM
2. stm32l4 devices we store the information on the internal FLASH using a library from ST which takes care of the FLASH life cycle.

One could also use an I2C or SPI EEPROM to store those settings. This would require the modification of eeprom-board.c file in order to handle the EEPROM I2C or SPI protocols.
