### ISSUE TITLE
Compliance Timing - Class C - Issue

### ISSUE THREAD

**Issue by userMF** [Lora-net/LoRaMac-node#861]
Hi everyone,

I found something strange while trying to send some compliance test's commands to my device.
I suspected my code, so I tried to use only the stack, but at the end got the same behaviour.

Long story short, I'm developing a product and it will go through compliance. But before that I need to check that it will not fail.
My code is based on the master branch: v4.4.3.
My device will be a C class and my hardware is the B-L072Z-LRWAN1.

When I put my device in the compliance test mode using the following downlink : 01010101 on the port 223 (To help me, I temporarily changed the compliance port to 223 - but it shouldn't matter here).
The system start to send the downlink counter has it should be doing.

BUT the timing between two messages are 10s or a little bit more ( sometime even 11s) and that is against the compliance requirements: (or this is limit...)
> Once in Test mode, the device shall send an uplink frame as quickly as possible ideally every 5
Seconds but worse case every 10 Seconds.

And worst, I can't manage to got a stable behaviour with the 04 commands. [The cryptography tests].
When I send 0400, my device should send me back 0401. But a lot of time i got nothing, via the prints in the code I'm able to know that my device receive the 0400 downlink but can't send an answer.

After some digging on why it take so long to send a message, I found that the stack wait for an ACK bit even in unconfirmed mode (the stack stay busy while this bit is not received or timeout):

```
if( ( MacCtx.NvmCtx->DeviceClass == CLASS_C ) || ( MacCtx.NodeAckRequested == true ) )
    {
        getPhy.Attribute = PHY_ACK_TIMEOUT;
        phyParam = RegionGetPhyParam( MacCtx.NvmCtx->Region, &getPhy );
        TimerSetValue( &MacCtx.AckTimeoutTimer, MacCtx.RxWindow2Delay + phyParam.Value );
        TimerStart( &MacCtx.AckTimeoutTimer );
    }
file : LoRaMaC.c
function: ProcessRadioTxDone
```
This is strange, as far as I understand the protocol this shouldn't append ... Right ?

**Comment by mluis1** [comment]
The certification process is currently meant only for Class A devices.
This means that one should run the certification tests only on a device running in Class A mode of operation even though the final product will operate as a Class C device.

The only differences when operating in Class C mode is that instead of setting the radio in sleep mode the stack sets the radio in reception with Rx2 parameters.

The `ACK_TIMEOUT` for Class C is there to ensure that the end-device is able correctly handle the second window.

Please note that the `ACK_TIMEOUT` was a confusing name and it has been changed in recent LoRaWAN specification versions. It has been renamed `RETRANSMIT_TIMEOUT`.

In case you still would like to perform the certification in Class C operation for the end-device I would recommend that the 5 seconds restriction between uplinks to be relaxed. 
This restriction was there in order to speed up the certification process. 
In recent updates of the certification specification this restriction has been removed form the specifications.
