### ISSUE TITLE
retransmission packets

### ISSUE THREAD

**Issue by Arcanum7** [Lora-net/LoRaMac-node#865]
Hi all! I have LoraMac  lib with stm32L072. (took it from STM32CubeExpansion_LRWAN_V1.2.1) 
I send frames every 5 min with ACK. It sends ok and rcv ok.
But sometimes frames send with repitition flag when before frame sended with ack ok.
Where i wrong?

**Comment by mluis1** [comment]
Unfortunately, you don't provide enough information.

A step by step procedure on how to reproduce the issue would be helpful. Providing small logs (end-device and network server) showing the issue is also helpful.

What do you mean by `repetition flag`? 
Such flag doesn't exist in the LoRaWAN specifications. The way to see if there was a repetition is if at least 2 frames have the same FCnt field value.

Please also note that STM32CubeExpansion_LRWAN_V1.2.1 is a fork of this project and there are differences. I would suggest that you address your question to ST support.
