### ISSUE TITLE
Single-channel operation with Dragino LG01-N

### ISSUE THREAD

**Issue by acutetech** [Lora-net/LoRaMac-node#880]
I am midway through porting this to a new platform (using Nordic Semiconductor nRF52832 Bluetooth processor). ping-pong works and I have moved to LoRaMac ClassA, which builds and runs on the hardware.

At present the only gateway available to me is the Dragino LG01-N, which is limited. (I have a full-function gateway on order). I do not seem to be talking to it. It transpires that the gateway only works with one channel at a time, and work-arounds are documented only for the LMIC library. The fix appears to be to change the end-node to use a single channel only, and perhaps also "enlarge RXtimeout". Changes to the code are given:
https://www.thethingsnetwork.org/forum/t/dragino-lg-01-connected-but-no-packets/27683/22

What changes can I make to work with the Dragino LG01-N? I suspect I need to alter the Radioxxxxx.c file(s).

**Comment by mluis1** [comment]
LG01-N is not a LoRaWAN gateway as all so called "single channel gateway" are not LoRaWAN gateways.

As such we can't provide support for something that is not LoRaWAN compliant.

I would recommend that you wait to receive your LoRaWAN gateway in order to validate your platform port.

As an hint to solve your current issue, there is no need to touch the radio drives. Instead look at changing the channel mask.
