### ISSUE TITLE
AS923-2 problem: short first and second uplink delay

### ISSUE THREAD

**Issue by wisang1999** [Lora-net/LoRaMac-node#952]
Hi, I'm trying to use the AS923-2 Frequency Plan, and I think the only changes needed on the node side for using this specification is changing default freq and Rx2 freq. I'm using this document for my reference: https://lora-alliance.org/sites/default/files/2020-02/rp_2-1.0.1.pdf. I think it's worked pretty well, but I have one problem here. The delay between the first and the second uplink is just like 3-4 seconds although I set the delay for 60 sec. Other than that, no problem with the delay on the next uplink. What I'm missing here? Any suggestion where the code part needs to pay attention to fix this? 

nb: I've tried to use combinations of nucleo073, nucleo476, sx1262mb2cas, and sx1276mb1las, but they produce the same results.

**Comment by mluis1** [comment]
Yes, the different AS923 plans are just frequency offsets an applies to default channels, Rx2 frequency and Beacon frequency.

Concerning the uplink periodicity this may be normal.  
The network server may schedule a `TxParamSetupReq` MAC command downlink on the first uplink Rx windows. The MAC layer will notify the application to schedule an uplink as soon as possible in order to validate the new parameters. So, this will end up having an uplink transmitted before the wanted periodicity expires.

I don't know which branch of this repository you are using but, it should only be necessary to choose which plan group one would like to use at compile time. This can be done by changing `REGION_AS923_DEFAULT_CHANNEL_PLAN` on `.vscode/settings.json` file.

```json
        // Default channel plan for region AS923. Possible selections:
        // CHANNEL_PLAN_GROUP_AS923_1, CHANNEL_PLAN_GROUP_AS923_2, CHANNEL_PLAN_GROUP_AS923_3, CHANNEL_PLAN_GROUP_AS923_1_JP
        "REGION_AS923_DEFAULT_CHANNEL_PLAN":"CHANNEL_PLAN_GROUP_AS923_1"
```

While looking at the current implementation I noticed some missing code on master branch. We will update the code as soon as possible.
In mean time the below patch can be applied
```patch
diff --git a/src/mac/region/RegionAS923.c b/src/mac/region/RegionAS923.c
index 3066dc46..e3b68517 100644
--- a/src/mac/region/RegionAS923.c
+++ b/src/mac/region/RegionAS923.c
@@ -71,6 +71,8 @@
 
 // Channel plan CHANNEL_PLAN_GROUP_AS923_1_JP
 
+#define REGION_AS923_FREQ_OFFSET          0
+
 /*!
  * Restrict AS923 frequencies to channels 24 to 38
  * Center frequencies 920.6 MHz to 923.4 MHz @ 200 kHz max bandwidth
@@ -90,12 +92,6 @@
 #undef AS923_RX_MAX_DATARATE
 #define AS923_RX_MAX_DATARATE             DR_5
 
-#undef AS923_DEFAULT_UPLINK_DWELL_TIME
-#define AS923_DEFAULT_UPLINK_DWELL_TIME   DR_5
-
-#undef AS923_DEFAULT_DOWNLINK_DWELL_TIME
-#define AS923_DEFAULT_DOWNLINK_DWELL_TIME DR_5
-
 #undef AS923_DEFAULT_MAX_EIRP
 #define AS923_DEFAULT_MAX_EIRP            13.0f
 
@@ -288,7 +284,7 @@ PhyParam_t RegionAS923GetPhyParam( GetPhyParams_t* getPhy )
         }
         case PHY_DEF_RX2_FREQUENCY:
         {
-            phyParam.Value = AS923_RX_WND_2_FREQ;
+            phyParam.Value = AS923_RX_WND_2_FREQ - REGION_AS923_FREQ_OFFSET;
             break;
         }
         case PHY_DEF_RX2_DR:
@@ -338,7 +334,7 @@ PhyParam_t RegionAS923GetPhyParam( GetPhyParams_t* getPhy )
         }
         case PHY_BEACON_CHANNEL_FREQ:
         {
-            phyParam.Value = AS923_BEACON_CHANNEL_FREQ;
+            phyParam.Value = AS923_BEACON_CHANNEL_FREQ - REGION_AS923_FREQ_OFFSET;
             break;
         }
         case PHY_BEACON_FORMAT:
@@ -406,6 +402,10 @@ void RegionAS923InitDefaults( InitDefaultsParams_t* params )
             NvmCtx.Channels[0] = ( ChannelParams_t ) AS923_LC1;
             NvmCtx.Channels[1] = ( ChannelParams_t ) AS923_LC2;
 
+            // Apply frequency offset
+            NvmCtx.Channels[0].Frequency -= REGION_AS923_FREQ_OFFSET;
+            NvmCtx.Channels[1].Frequency -= REGION_AS923_FREQ_OFFSET;
+
             // Default ChannelsMask
             NvmCtx.ChannelsDefaultMask[0] = LC( 1 ) + LC( 2 );
```
