### ISSUE TITLE
Which version is this?

### ISSUE THREAD

**Issue by gpgib6** [Lora-net/LoRaMac-node#958]
Main question: If someone asks me, which version of the LoRa stack are we using, where can I find this in the code?
Additional comments and questions:
I'm so confused by the versioning you guys are using.
My code is using the LoRa stack that came from the feature/5.0.0 branch. If that is version 5.0.0 then what is Release Version 5.0.0? And for Release Version 5.0.0 it says 100% complete and no due date but the description says "Within this milestone, we **will** add the support..."
Why do you have 3 branches but you only describe 2 of them, is the feature/5.0.0 branch about to be deleted?
What kind of version number is 2-1.0.1, that just looks super confusing.
It says "This milestone will be based on LoRaWAN Specification 1.0.4 LoRaWAN Specification 1.1.1"... which one is it?
Inside the code it says this:
    Version_t lrWanVersion;
    lrWanVersion.Fields.Major    = 1;
    lrWanVersion.Fields.Minor    = 1;
    lrWanVersion.Fields.Revision = 1;
    lrWanVersion.Fields.Rfu      = 0;
    MacCtx.NvmCtx->Version = lrWanVersion;

Is that the version?
I would really love it if you guys can create one document that describes all the different branches and versions.

**Comment by mluis1** [comment]
You are right there are too many versions to handle and it can be quite confusing at start.

To summarize there is a version for
- This project
- LoRaWAN specification
- LoRaWAN regional parameters specification

In plus to these the LoRa-Alliance currently has 3 different active versions of the LoRaWAN specification 
- 1.0.3
- 1.0.4 to be released soon
- 1.1.1 (under development by the LoRa-Alliance)

And 2 active versions of the LoRaWAN regional parameters specification

- 1.0.3revA - Linked to LoRaWAN 1.0.3 specification
- RP2-1.0.1 - Linked to LoRaWAN 1.0.4 and 1.1.1.

Recently the LoRa-Alliance has released a new version of the LoRaWAN regional parameters named RP2-1.0.2 (not yet handled by this project)

The [README.md](https://github.com/Lora-net/LoRaMac-node/blob/master/README.md) file has just been updated trying to reflect all these versions relation to this project.
The new table is as follows:
| Branch        | L2 spec       | RP spec   | Tag/Milestone       | Class     | Comments      |
| ------------- |:-------------:|:---------:|:---------:|:---------:|:--------------|
| | [1.0.3](https://lora-alliance.org/resource-hub/lorawanr-specification-v103) | [v1.0.3revA](https://www.lora-alliance.org/resource-hub/lorawanr-regional-parameters-v103reva) | [v4.4.4](https://github.com/Lora-net/LoRaMac-node/releases/tag/v4.4.4) | A/B/C | LoRaWAN L2 1.0.3 - **_Released_** |
| [master](https://github.com/Lora-net/LoRaMac-node/tree/master) | [1.0.3](https://lora-alliance.org/resource-hub/lorawanr-specification-v103) | [v1.0.3revA](https://www.lora-alliance.org/resource-hub/lorawanr-regional-parameters-v103reva) | [M 4.4.5](https://github.com/Lora-net/LoRaMac-node/milestone/7) | A/B/C | LoRaWAN L2 1.0.3 |
| [develop](https://github.com/Lora-net/LoRaMac-node/tree/develop) | [1.0.4](https://lora-alliance.org/resource-hub) | [2-1.0.1](https://lora-alliance.org/sites/default/files/2020-02/rp_2-1.0.1.pdf) | [M 4.5.0](https://github.com/Lora-net/LoRaMac-node/milestone/5) | A/B/C |  LoRaWAN L2 1.0.4 |
| [feature/5.0.0](https://github.com/Lora-net/LoRaMac-node/tree/feature/5.0.0) | [1.0.4](https://lora-alliance.org/resource-hub) / [1.1.1](https://lora-alliance.org/resource-hub/lorawanr-specification-v11) | [2-1.0.1](https://lora-alliance.org/sites/default/files/2020-02/rp_2-1.0.1.pdf) | [M 5.0.0](https://github.com/Lora-net/LoRaMac-node/milestone/3) | A/B/C |  LoRaWAN L2 1.0.4 / 1.1.1 |

The first line in the table provides the description of latest release performed on this project.
The second line (master branch) provides the changes to be include on the next release. (LoRaWAN 1.0.3 specification only)
The third line (develop branch) provides the changes required to handle the LoRaWAN 1.0.4 specification only
The forth line (feature/5.0.0) provides the changes required to handle the LoRaWAN 1.1.1 specification (this branch also handles LoRaWAN 1.0.4 specification when connected to a 1.0.x Network server)

Thus, the releases are currently based on LoRaWAN 1.0.3 specification and are tagged `v4.4.x` where `x` is the revision.
The LoRaWAN 1.0.4 specification code base will be tagged in the future as `v4.5.x`. When this happens the LoRaWAN 1.0.3 specification support will be stopped.
The LoRaWAN 1.0.4/1.1.1 specification code base will be tagged in the future as `v5.0.x`. Hopefully in the future this will become the only active development which should considerably simplify everything.

Also, to clarify why some milestones are empty. The reason is that this project development takes place privately between Stackforce and Semtech. Time to time we synchronize our internal repositories with GitHub.
This means that on the GitHub milestones, one will see only the issues/merge-requests issued by the GitHub users.

Concerning your question on how to know which version the stack is currently handling you can issue the following command once the end-device is connected to a Network Server.

```c
            Version_t           lrwanVersion;
            Version_t           lrwanRpVersion;
            MibRequestConfirm_t mibReq;

            mibReq.Type = MIB_LORAWAN_VERSION;

            LoRaMacMibGetRequestConfirm( &mibReq );
            lrwanVersion   = mibReq.Param.LrWanVersion.LoRaWan;
            lrwanRpVersion = mibReq.Param.LrWanVersion.LoRaWanRegion;
```
